services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ecfr
      POSTGRES_USER: ecfr
      POSTGRES_PASSWORD: ecfr
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecfr -d ecfr"]
      interval: 5s
      timeout: 5s
      retries: 10

