create table agencies (
  slug varchar(255) primary key,
  name varchar(255) not null,
  short_name varchar(64),
  word_count integer not null,
  checksum varchar(64) not null,
  topic_count integer not null,
  latest_amended_on date
);

create table agency_topics (
  id bigint generated by default as identity primary key,
  agency_slug varchar(255) not null references agencies(slug) on delete cascade,
  topic_key varchar(255) not null,
  title integer not null,
  chapter varchar(64),
  subtitle varchar(64),
  subchapter varchar(64),
  part varchar(64),
  word_count integer not null,
  checksum varchar(64) not null,
  raw_xml text not null,
  preview_text text not null,
  view_count integer not null default 0,
  last_viewed_at timestamp,
  unique (agency_slug, topic_key)
);

create table agency_change_months (
  agency_slug varchar(255) not null references agencies(slug) on delete cascade,
  month_start date not null,
  amendment_count integer not null,
  removal_count integer not null,
  primary key (agency_slug, month_start)
);

create index agency_topics_views_idx on agency_topics(agency_slug, view_count desc);
